<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="A8344F1D" name="com.vl.qa.runner.TestRunner" tests="1" failures="0" timestamp="06 Nov 2017 07:18:41 GMT" time="26.569" errors="1">
  <testcase name="feature" time="26.569" classname="com.vl.qa.runner.TestRunner">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false],
	&lt;b style=&#039;background-Tomato;&#039;&gt;Scenario failed due to the response time is greater than 10secs&lt;/b&gt;">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false],
	<b style='background-Tomato;'>Scenario failed due to the response time is greater than 10secs</b>
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:134)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:118)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false],
	<b style='background-Tomato;'>Scenario failed due to the response time is greater than 10secs</b>
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.vl.qa.baseutils.CustomAsserts.softAssert(CustomAsserts.java:18)
	at com.vl.qa.steps.Login_test.verify_user_is_logged_into_the_site(Login_test.java:43)
	at âœ½.Then verify user is logged into the site(VerifyLogin.feature:7)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- com.vl.qa.runner.TestRunner -->
